# configuration file for SOPS/encryption
creation_rules:
  - path_regex: values\.cloud\.yaml$
    kms: 'arn:aws:kms:us-west-2:503561456208:key/8f487e8c-d6c5-4ed4-9ace-c5011baead84,arn:aws:kms:us-east-1:503561456208:key/4ce4551c-4b42-4e0a-ac14-961f385c9517'
