# Project Information
site_name: Post-disaster Communications

# Repository
repo_name: uw-ssec/post-disaster-comms
repo_url: https://github.com/uw-ssec/post-disaster-comms

# Configuration
theme:
  name: material
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: amber
  font:
    text: Roboto
    code: Roboto Mono

# Additional Configuration
extra:
  social:
    - icon: fontawesome/brands/chrome
      link: https://escience.washington.edu/software-engineering/ssec/
    - icon: fontawesome/brands/github
      link: https://github.com/uw-ssec/

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption