[project]
name = "post-disaster-comms"
version = "0.1.0"
description = "post-disaster communications project"
authors = ["Don Setiawan"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.10"
ipykernel = ">=6.29.5,<6.30"
rich = ">=13.7.1,<13.8"
ruby = ">=3.3.3,<3.4"
curl = ">=8.8.0,<8.9"
kubernetes-helm = ">=3.15.3,<3.16"
kubernetes-client = ">=1.23.6,<1.31"

[tasks]
install-tools = { depends-on = ["install-k3d", "install-flutter", "fetch-supabase-chart"] }
setup-infra = { depends-on = ["k3d-create-cluster", "set-registry-secret", "setup-supabase"] }

# Supabase tasks
[tasks.set-registry-secret]
# This task will need docker username and password
# to be set as environment variables
# DOCKER_USERNAME and DOCKER_PASSWORD
cmd = "scripts/docker-login.sh"

[tasks.fetch-supabase-chart]
cmd = "git submodule update --init"

[tasks.setup-supabase]
cmd = [
    "helm",
    "upgrade",
    "supabase", 
    "vendors/supabase-kubernetes/charts/supabase",
    "--install",
    "--wait",
    "--cleanup-on-fail",
    "--values",
    "deployment/values.dev.yaml"
]
depends-on = ["fetch-supabase-chart"]

# K3D Tasks
[tasks.install-k3d]
cmd = "curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash"
outputs = ["**/bin/k3d"]

[tasks.install-k3d.env]
K3D_INSTALL_DIR = "$CONDA_PREFIX/bin"
USE_SUDO = "false"

[tasks.k3d-create-cluster]
cmd = [
    "k3d",
    "cluster",
    "create",
    "pdc-cluster",
    "-p", "80:80@loadbalancer",
    "-p", "5432:5432@loadbalancer",
]
depends-on = ["install-k3d", "k3d-delete-cluster"]

[tasks.k3d-delete-cluster]
cmd = "k3d cluster delete pdc-cluster"

# Flutter tasks
[tasks.flutter-run]
cmd = "flutter run"
cwd = "src/support_sphere"
depends-on = ["flutter-devices", "flutter-get"]

[tasks.flutter-get]
cmd = "flutter pub get"
cwd = "src/support_sphere"
depends-on = ["check-flutter"]

[tasks.flutter-devices]
cmd = "flutter devices"
cwd = "src/support_sphere"
depends-on = ["check-flutter"]

[tasks.install-flutter]
cmd = "python scripts/install-flutter.py"
outputs = [".app/flutter"]

[tasks.check-flutter]
cmd = "flutter doctor"
depends-on = ["install-flutter"]
