secret:
  jwt:
    anonKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
    serviceKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
    secret: your-super-secret-jwt-token-with-at-least-32-characters-long
  smtp:
    username: your-mail@example.com
    password: example123456
  dashboard:
    username: supabase
    password: this_password_is_insecure_and_should_be_updated
  db:
    username: postgres
    password: example123456
    database: postgres
  analytics:
    apiKey: your-super-secret-and-long-logflare-key

db:
  imagePullSecrets:
  - name: regcred
  enabled: true
  image:
    repository: ghcr.io/uw-ssec/supabase-db
    tag: 2024.09.13
  livenessProbe:
    exec:
      command:
        - pg_isready
        - -U
        - postgres
    initialDelaySeconds: 3
  persistence:
    enabled: false
  config:
    # Enable the PostGIS extension on deployment
    postgis.sql: |
      BEGIN;
        -- Create postgis extension
        CREATE EXTENSION IF NOT EXISTS postgis SCHEMA extensions;
      COMMIT;

studio:
  imagePullSecrets:
  - name: regcred
  image:
    repository: ghcr.io/uw-ssec/supabase-studio
    tag: 2024.09.13
  environment:
    STUDIO_DEFAULT_ORGANIZATION: "My Organization"
    STUDIO_DEFAULT_PROJECT: "My Project"
    SUPABASE_PUBLIC_URL: http://localhost/
    NEXT_PUBLIC_ENABLE_LOGS: "true"
  livenessProbe:
    httpGet:
      path: /api/profile
      port: 3000
    initialDelaySeconds: 3

auth:
  imagePullSecrets:
  - name: regcred
  image:
    repository: ghcr.io/uw-ssec/supabase-auth
    tag: 2024.09.13
  environment:
    API_EXTERNAL_URL: http://localhost
    GOTRUE_SITE_URL: http://localhost
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    GOTRUE_MAILER_AUTOCONFIRM: "true"
    GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@example.com"
    GOTRUE_SMTP_HOST: "smtp.example.com"
    GOTRUE_SMTP_PORT: "587"
    GOTRUE_SMTP_SENDER_NAME: "your-mail@example.com"
    GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_ENABLED: "true"
    GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_URI: "pg-functions://postgres/public/custom_access_token"

rest:
  imagePullSecrets:
  - name: regcred
  image:
    repository: ghcr.io/uw-ssec/supabase-rest
    tag: 2024.09.13

realtime:
  # Override the fullname of the realtime deployment
  # as this is needed by supabase realtime to work properly
  # See: https://github.com/supabase-community/supabase-kubernetes/issues/74
  fullnameOverride: "realtime-dev"
  imagePullSecrets:
  - name: regcred
  image:
    repository: ghcr.io/uw-ssec/supabase-realtime
    tag: 2024.09.13
  livenessProbe:
    httpGet:
      path: /
      port: 4000
    initialDelaySeconds: 3

meta:
  imagePullSecrets:
  - name: regcred
  image:
    repository: ghcr.io/uw-ssec/supabase-meta
    tag: 2024.09.13

storage:
  imagePullSecrets:
  - name: regcred
  image:
    repository: ghcr.io/uw-ssec/supabase-storage
    tag: 2024.09.13
  livenessProbe:
    httpGet:
      path: /status
      port: 5000
    initialDelaySeconds: 3
  persistence:
    enabled: false

imgproxy:
  imagePullSecrets:
  - name: regcred
  image:
    repository: ghcr.io/uw-ssec/supabase-imgproxy
    tag: 2024.09.13
  environment:
    IMGPROXY_ENABLE_WEBP_DETECTION: "true"
  livenessProbe:
    exec:
      command:
        - imgproxy
        - health
    initialDelaySeconds: 3
  persistence:
    enabled: false

kong:
  imagePullSecrets:
  - name: regcred
  image:
    repository: ghcr.io/uw-ssec/supabase-kong
    tag: 2024.09.13
  environment:
    KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
    KONG_LOG_LEVEL: info
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    tls: []
      # - secretName: example-ingress-tls
      #   hosts:
      #     - example.com
    hosts:
      - host: localhost
        paths:
          - path: /
            pathType: Prefix

analytics:
  imagePullSecrets:
  - name: regcred
  image:
    repository: ghcr.io/uw-ssec/supabase-analytics
    tag: 2024.09.13
  livenessProbe:
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 3

vector:
  imagePullSecrets:
  - name: regcred
  image:
    repository: ghcr.io/uw-ssec/supabase-vector
    tag: 2024.09.13
  livenessProbe:
    httpGet:
      path: /health
      port: 9001
    initialDelaySeconds: 3
  ## Vector requires logs from the control plane to function.
  ## This is normally stored in /var/log/pods
  ## Modify these values according to your environment.
  volumeMounts:
    - name: pod-logs
      mountPath: /var/log/pods
  volumes:
    - name: pod-logs
      hostPath:
        path: /var/log/pods

functions:
  imagePullSecrets:
  - name: regcred
  image:
    repository: ghcr.io/uw-ssec/supabase-functions
    tag: 2024.09.13
