analyzer:
  errors:
    no_logic_in_create_state: ignore
  exclude:
    - lib/data/models/generated_classes.dart
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
