import 'dart:ffi';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:support_sphere/utils/supabase.dart';


class MessageService {
  final SupabaseClient _supabaseClient = supabase;

  /*
  create table if not exists local_messages (
      id int generated by default as identity primary key,
      message text not null,
      code text,
      location gis.geography(POINT) not null);

  create index messages_geo_index
      on public.restaurants
      using GIST (location);

  create or replace function nearby_messages(lat float, long float)
  returns table (id local_messages.id%TYPE, name local_messages.name%TYPE, lat float, long float, dist_meters float)
  set search_path = ''
  language sql
  as $$
    select id, name, gis.st_y(location::gis.geometry) as lat, gis.st_x(location::gis.geometry) as long, gis.st_distance(location, gis.st_point(long, lat)::gis.geography) as dist_meters
    from local_messages
    order by location operator(gis.<->) gis.st_point(long, lat)::gis.geography;
  $$;

  grant usage on schema gis to anon, authenticated;
  */

  init() async {
    FirebaseMessaging messaging = FirebaseMessaging.instance;

    NotificationSettings settings = await messaging.requestPermission(
      alert: true,
      announcement: false,
      badge: true,
      carPlay: false,
      criticalAlert: false,
      provisional: false,
      sound: true,
    );

    print('User granted permission: ${settings.authorizationStatus}');
  }

  Future<PostgrestList?> getTopics() async {
    // FIXME - Implement DB
    return await _supabaseClient.from('local_messages').select('''
      people(
        id,
        user_profile_id,
        given_name,
        family_name,
        nickname,
        is_safe,
        needs_help
      )
    ''');
  }

  /// Get messages for a topic
  Future<PostgrestList?> getMessagesForTopic(String topicId) async {
    // FIXME - Implement DB
    return await _supabaseClient.from('local_messages').select('''
      people(
        id,
        user_profile_id,
        given_name,
        family_name,
        nickname,
        is_safe,
        needs_help
      )
    ''').eq('household_id', topicId);
  }

  /// Get messages for a user
  Future<PostgrestList?> getMessagesForUser(String userId) async {
    // FIXME - Implement DB
    return await _supabaseClient.from('local_messages').select('''
      people(
        id,
        user_profile_id,
        given_name,
        family_name,
        nickname,
        is_safe,
        needs_help
      )
    ''').eq('household_id', userId);
  }

  /// Get messages associated with a location.
  Future<PostgrestList?> getMessagesForLocation(Float latitude, Float longitude, Float distance) async {
    return await _supabaseClient.rpc('nearby_messages', params: {
      'lat': latitude,
      'long': longitude,
    });
  }

  /// Add a message with location
  addMessageWithLocation(String msg, String code, Float latitude, Float longitude) async {
    await _supabaseClient.from('local_messages')
      .insert({
        'message': msg,
        'code': code,
        'location': 'POINT($latitude $longitude)'
      });
  }
}